web/duncan-chess-academy/setup/webapp/server/game/views.py
from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_required

from webapp.server import db
from webapp.server.models import ChessGame
from webapp.server.game.forms import AddGameForm


game_blueprint = Blueprint("game", __name__)

# Comment out in production ... only need this in dev...
# @game_blueprint.route("/add", methods=["GET", "POST"])
# @login_required
def add():
    form = AddGameForm(request.form)
    if request.method == "POST":
        if form.validate_on_submit():
            game = ChessGame(
                id=form.id.data,
                rated=form.rated.data,
                turns=form.turns.data,
                victory_status=form.victory_status.data,
                winner=form.winner.data,
                opening_name=form.on.data,
                moves=form.moves.data
            )
            db.session.add(game)
            db.session.commit()

            flash("Game Added Successfully!", "success")
            return redirect(url_for("user.members"))
        else:

            for fieldName, errorMessages in form.errors.items():
                for err in errorMessages: 
                    print(fieldName, err)
    
    return render_template("game/add.html", form=form)

web/duncan-chess-academy/setup/webapp/server/main/views.py
from werkzeug.utils import redirect

from flask.helpers import url_for
from flask import Blueprint

main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/", methods=["GET"])
def home():
    return redirect(url_for("user.login"))

web/duncan-chess-academy/setup/webapp/server/user/views.py
import pandas as pd

from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required, current_user

from webapp.server import bcrypt, db
from webapp.server.models import User
from webapp.server.user.forms import LoginForm, RegisterForm, FilterForm
from webapp.server.models import ChessGame
from webapp.server.game.views import add

user_blueprint = Blueprint("user", __name__)


@user_blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None:
            flash("User with this email already exists!", "danger")
        else:
            user = User(email=form.email.data, password=form.password.data)
            db.session.add(user)
            db.session.commit()

            login_user(user)

            flash("Thank you for registering.", "success")
            return redirect(url_for("user.members"))

    return render_template("user/register.html", form=form)


@user_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("user.members"))

    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
            user.password, request.form["password"]
        ):
            login_user(user)
            flash("You are logged in. Welcome!", "success")
            return redirect(url_for("user.members"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("user/login.html", form=form)
    return render_template("user/login.html", title="Please Login", form=form)


@user_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out. Bye!", "success")
    return redirect(url_for("main.home"))


@user_blueprint.route("/members", methods=["GET", "POST"])
@login_required
def members():
    games_df = pd.DataFrame(
        [
            {
                "id": g.id,
                "opening_name": g.opening_name,
                "winner": g.winner,
                "moves": g.moves,
                "victory_status": g.victory_status,
                "rated": g.rated,
                "turns": g.turns,
            }
            for g in ChessGame.query.all()
        ]
    )

    form = FilterForm(request.form)
    form.opening_name.choices = [""] + list(games_df["opening_name"].unique())
    form.victory_status.choices = [""] + list(games_df["victory_status"].unique())
    form.winner.choices = [""] + list(games_df["winner"].unique())

    if request.method == "POST":
        if form.validate():
            searchable_fields = [
                "winner",
                "opening_name",
                "victory_status",
                "rated",
                "turns",
            ]

            for field, value in request.form.items():
                if value and field in searchable_fields:
                    games_df = games_df.query(f"{field} == '{value}'")

        else:
            flash("Error submitting filter form", "danger")

    return render_template(
        "user/members.html", form=form, games=games_df.to_dict(orient="records")
    )

web/duncan-chess-academy/setup/webapp/client/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Duncan Chess Academy {% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='dataTables.bootstrap4.min.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
              {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}

        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

web/duncan-chess-academy/setup/webapp/client/templates/footer.html
<footer>
  <nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="container">
      <small>
        <span>©
          <a href="#">Duncan Chess Academy</a>
        </span>
      </small>
    </div>
  </nav>
</footer>

web/duncan-chess-academy/setup/webapp/client/templates/header.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <!-- Navbar Brand -->
    <a class="navbar-brand" href="{{ url_for('main.home') }}">Chess Academy</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Main Navigation -->
      <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.members') }}">Members</a>
        </li>
        {% if current_user.admin %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('game.add') }}">Add Game</a>
        </li>
        {% endif %}
        {% endif %}
      </ul>
      <!-- Login/Logout -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          {% if current_user.is_authenticated %}
          <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
          {% else %}
          <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>