web/duncan-chess-academy/setup/webapp/server/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, IntegerField, SelectField
from wtforms.validators import DataRequired, Email, Length, EqualTo, Optional


class LoginForm(FlaskForm):
    email = StringField("Email Address", [DataRequired(), Email()])
    password = PasswordField("Password", [DataRequired()])


class RegisterForm(FlaskForm):
    email = StringField(
        "Email Address",
        validators=[
            DataRequired(),
            Email(message=None),
            Length(min=6, max=40),
        ],
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Confirm password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )


class FilterForm(FlaskForm):
    winner = SelectField(
        "Winner",
        validators=[Optional()],
    )
    opening_name = SelectField(
        "Opening Name",
        validators=[Optional()],
    )
    rated = StringField("Rated", [Length(max=10)])
    turns = IntegerField("Turns", [Optional()])
    victory_status = SelectField(
        "Victory Status",
        validators=[Optional()],
    )

web/duncan-chess-academy/setup/webapp/server/user/views.py
import pandas as pd

from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required, current_user

from webapp.server import bcrypt, db
from webapp.server.models import User
from webapp.server.user.forms import LoginForm, RegisterForm, FilterForm
from webapp.server.models import ChessGame
from webapp.server.game.views import add

user_blueprint = Blueprint("user", __name__)


@user_blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None:
            flash("User with this email already exists!", "danger")
        else:
            user = User(email=form.email.data, password=form.password.data)
            db.session.add(user)
            db.session.commit()

            login_user(user)

            flash("Thank you for registering.", "success")
            return redirect(url_for("user.members"))

    return render_template("user/register.html", form=form)


@user_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("user.members"))

    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
            user.password, request.form["password"]
        ):
            login_user(user)
            flash("You are logged in. Welcome!", "success")
            return redirect(url_for("user.members"))
        else:
            flash("Invalid email and/or password.", "danger")
            return render_template("user/login.html", form=form)
    return render_template("user/login.html", title="Please Login", form=form)


@user_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out. Bye!", "success")
    return redirect(url_for("main.home"))


@user_blueprint.route("/members", methods=["GET", "POST"])
@login_required
def members():
    games_df = pd.DataFrame(
        [
            {
                "id": g.id,
                "opening_name": g.opening_name,
                "winner": g.winner,
                "moves": g.moves,
                "victory_status": g.victory_status,
                "rated": g.rated,
                "turns": g.turns,
            }
            for g in ChessGame.query.all()
        ]
    )

    form = FilterForm(request.form)
    form.opening_name.choices = [""] + list(games_df["opening_name"].unique())
    form.victory_status.choices = [""] + list(games_df["victory_status"].unique())
    form.winner.choices = [""] + list(games_df["winner"].unique())

    if request.method == "POST":
        if form.validate():
            searchable_fields = [
                "winner",
                "opening_name",
                "victory_status",
                "rated",
                "turns",
            ]

            for field, value in request.form.items():
                if value and field in searchable_fields:
                    games_df = games_df.query(f"{field} == '{value}'")

        else:
            flash("Error submitting filter form", "danger")

    return render_template(
        "user/members.html", form=form, games=games_df.to_dict(orient="records")
    )

web/duncan-chess-academy/setup/webapp/client/templates/user/login.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

  <header class="content-header">
    <h1>Login</h1>
    <hr><br>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <div class="col-lg-4 col-sm-4">
      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}

      <button class="btn btn-success" type="submit">Sign In!</button>
      <br><br>
      <p>Need to <a href="{{ url_for('user.register') }}">Register</a>?</p>
    </div>
  </form>

{% endblock %}

web/duncan-chess-academy/setup/webapp/client/templates/user/members.html
{% extends "_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<div>
  <h1>Welcome to Duncan Chess Academy!</h1>
  <hr><br>
  <p>Use the filters below to search for historical chess games and study them</p>
  <hr><br>
  <form class="form" role="form" method="post" action="">
    {{ form.csrf_token }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <div class="row">
      <div class="col-lg-3 col-md-4 col-sm-6">
        {{ wtf.form_field(form.opening_name) }}
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        {{ wtf.form_field(form.victory_status) }}
      </div>
      <div class="col-lg-2 col-md-4 col-sm-6">
        {{ wtf.form_field(form.winner) }}
      </div>
      <div class="col-lg-2 col-md-4 col-sm-6">
        {{ wtf.form_field(form.rated) }}
      </div>
      <div class="col-lg-2 col-md-4 col-sm-6">
        {{ wtf.form_field(form.turns) }}
      </div>
    </div>

    <div class="col-lg-2 col-md-4 col-sm-4">
      <button class="btn btn-success" type="submit">Search</button>
    </div>
  </form>

  <br />
  <table id="games-table" class="table table-striped table-bordered" style="width:100%">
    <thead>
      <tr>
        <th>ID</th>
        <th>Rated</th>
        <th>Turns</th>
        <th>Vistory Status</th>
        <th>Winner</th>
        <th>Opening Name</th>
        <th>Moves</th>
      </tr>
    </thead>
    <tbody>
      {% for game in games %}
      <tr >
        <th>{{ game['id'] }}</th>
        <th>{{ game['rated'] }}</th>
        <th>{{ game['turns'] }}</th>
        <th>{{ game['victory_status'] }}</th>
        <th>{{ game['winner'] }}</th>
        <th>{{ game['opening_name'] }}</th>
        <th>{{ game['moves'] }}</th>
      </tr> 
      {% endfor %}
      
    </tbody>
  </table>
</div>

{% endblock %}

web/duncan-chess-academy/setup/webapp/client/templates/user/register.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

  <header class="content-header">
    <h1>Register</h1>
    <hr><br>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <div class="col-lg-4 col-sm-4">
      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}
      {{ wtf.form_field(form.confirm) }}

      <button class="btn btn-success" type="submit">Register!</button>
      <br><br>
      <p>Already have an account? <a href="{{ url_for('user.login') }}">Sign in</a>.</p>
    </div>
  </form>

{% endblock %}